Tulia/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
   PasswordResetDoneView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'Shoppy'
urlpatterns =[
   # path('', views.setcookie)
   path('', views.home, name='shoppy-home'),
   path('cart/', views.cart, name='shoppy-cart'),
   path('register/', views.buyer_register, name='shoppy-buyer-reg'),
   path('seller_register/', views.seller_register, name='shoppy-seller-reg'),
   path('login/', views.user_login, name='shoppy-login'),
   path('logout/', views.logout_view, name='shoppy-logout'),
   path('products_list/<int:category_id>/', views.productsList, name='product_list'),
   path('user_account/' , views.user_account, name='shoppy-user_account' ),
   path('checkout/' , views.checkout, name='shoppy-view_checkout' ),
   path('search/' , views.search, name="searchbar" ),

   path('howtopay/', views.how_to_pay, name='how_to_pay'),

   path('product_filter/', views.product_filter, name='product_filter'),




   #wishlist
   path('add_to_wishlist/<int:product_id>/<str:source>' , views.addToWishlist, name='add_to_wishlist' ),
   path('remove_from_wishlist/<int:wishlist_id>/<str:source>' , views.unWishProduct, name='remove_from_wishlist' ), #delete wishlist/unwished
   path('remove_from_wishlist/all/' , views.unWish_All_Products, name='remove_all_from_wishlist' ), #delete all wishlist/unwished

   #view product details
   path('details/<int:product_id>/', views.productDetails, name='shoppy_product_details'),
         # reviews
         # path('make_reviews/', views.productReview, name='shoppy_product_review'),

   #cart
   path('cart/', views.cart, name='shoppy-cart'),
   path('addto/cart/<int:product_id>/', views.addCart, name='shoppy-add-cart'),
   path('deletefrom/cart/<int:order_id>/', views.deleteCartProduct, name='shoppy_delete_cart_product'),

   # checkout
   path('confirmcheckout/', views.confirmCheckout, name='shoppy-checkout'),

   # useraccount password change
   path('user_account/change_password', views.change_password, name='change_password'),

   # password reset

   path('pin_reset/', views.password_resett, name='password_resett'),
   # path('getpinShortcode/', views.getShortcode, name='getpinShortcode'),
   # path('verifyCode/', views.verifyCode, name='verifyCode'),
   # path('verifypassword/', views.verifypassword, name='verifypassword'),
   path('pin_confirm/', views.pin_confirmm, name='password_confirmm'),
   path('new_pin/', views.new_pin, name='new_pin'),



   # path('password_reset/', auth_views.PasswordResetView.as_view(
   #    template_name='shoppy/registration/password_reset.html',
   #    email_template_name='shoppy/registration/password_reset_email.html',
   #    subject_template_name='shoppy/registration/password_reset_subject.txt',
   #    success_url=reverse_lazy('Shoppy:password_reset_done')
   # ), name='password_reset'),
   #
   # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
   #    template_name='shoppy/registration/password_reset_done.html',
   # ), name='password_reset_done'),
   #
   # path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
   #    template_name='shoppy/registration/password_reset_confirm.html',
   #    success_url=reverse_lazy('Shoppy:password_reset_complete')
   # ), name='password_reset_confirm'),
   #
   # path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
   #    template_name='shoppy/registration/password_reset_complete.html',
   # ), name='password_reset_complete'),

   path('deleteme/', views.deleteme, name= 'deleteme'),





]

Tulia_admin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from Tulia_admin import views
from Tulia_admin.views import GeneratePDF, GenerateProductPDF
from clare_project import settings
app_name='TuliaAdmin'
urlpatterns = [

    path('', views.home , name='home'),
    path('logout/', views.logout_view, name='logout'),

    path('products/', views.products , name='products'),
    path('addproducts/', views.addproducts , name='addproducts'),
    path('deleteproducts/<int:product_id>', views.deleteproducts , name='deleteproducts'),
    path('featured/product/change/status/', views.product_featured, name='product_featured'),

    path('category/', views.category , name='category'),
    path('addcategory/', views.addcategory , name='addcategory'),
    path('deletecategory/<int:category_id>', views.deletecategory, name='delete_category'),
    path('editcategory/<int:category_id>', views.editcategory, name='edit_category'),
    path('view_sub_category/<int:category_id>', views.view_sub_category, name='view_sub_category'),

    path('brand/', views.brand , name='brand'),
    path('add_brand/', views.add_brand, name='add_brand'),
    path('delete/brand/<int:brand_id>', views.brand_delete, name='delete_brand'),
    path('edit/brand/<int:brand_id>', views.brand_edit, name='brand_edit'),



    path('carousel/', views.carousel , name='carousel'),
    path('addcarousel/', views.addcarousel , name='addcarousel'),
    path('carousel/delete/<int:carousel_id>', views.carousel_delete, name='carousel-delete'),
    path('carousel/edit/<int:carousel_id>', views.carousel_edit, name='carousel-edit'),

    path('variants/', views.variants, name='variants'),
    path('addvariants/', views.addvariants, name='addvariants'),
    path('variants/delete/<int:variant_id>', views.variant_delete, name='variant_delete'),
    path('variants/edit/<int:variant_id>', views.variant_edit, name='variant_edit'),

   path('variantsOptions/add/', views.variants_options, name='variants-options'),
   path('variantsOptions/delete/<int:variant_option_id>', views.variants_options_delete, name='variants-options-delete'),
   path('variantsOptions/edit/<int:variant_option_id>', views.variants_options_edit, name='variants-options-edit'),

    path('viewregions/', views.view_regions, name='view-regions'),
    path('regions/edit/<int:region_id>', views.edit_regions, name='edit-regions'),
    path('regions/delete/<int:region_id>', views.delete_regions, name='delete-regions'),


    path('orders/', views.orders, name='orders'),
    path('buyerOrders/<str:reference_code>', views.buyerOrders, name='buyer_orders'),

    path('payments/', views.payments, name='payments'),
    path('editpayments/<int:Order_payment_id>', views.edit_payments, name='updated_payments'),

    path('orders/chart/', views.ListOrders, name='orders_chart'),

    path('allreports/', views.viewAllReports, name='view_all_reports'),
    path('pdf/orders/', GeneratePDF.as_view(), name='orders_generated_pdf'),
    path('productspdf/', GenerateProductPDF.as_view(), name='products_generated_pdf'),

]

clare_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from clare_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Tulia.urls')),
    path('tuliaadmin/', include('Tulia_admin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tulia/models.py
from django.db import models

# Create your models here.

Tulia/views.py
import json

import africastalking
import os

import sweetify


from django.contrib.auth.decorators import login_required, permission_required
from django.core.mail import send_mail
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout, login, get_user_model
from django.utils.crypto import get_random_string
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
# import africastalking
from django.views.decorators.csrf import csrf_exempt
# from requests import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny

# from Tulia_admin.models import *
# from clare_project import settings
# from Tulia_admin.models import *
from clare_project import settings
from .forms import *


# Create your views here.

# # Base method with no type specified
# sweetify.sweetalert(self.request, 'Westworld is awesome', text='Really... if you have the chance - watch it!' persistent='I agree!')
#
# # Additional methods with the type already defined
# sweetify.info(self.request, 'Message sent', button='Ok', timer=3000)
# sweetify.success(self.request, 'You successfully changed your password')
# sweetify.error(self.request, 'Some error happened here - reload the site', persistent=':(')
# sweetify.warning(self.request, 'This is a warning... I guess')




def search(request):

    if request.method=="POST":
        search_text = request.POST['search_text']
        print(search_text)
    else:
        search_text =""

    products = Product.objects.filter(name__contains=search_text, status='VERIFIED' )
    context={
        'products': products,
        'search_text': search_text,
    }
    return render('shoppy/search.html',context)

def home(request):
    user = request.user
    carousels =Carousel.objects.order_by("-created_at")
    brand = Brand.objects.order_by('?').first()
    products = Product.objects.order_by("?")
    featured_products = Product.objects.filter(feat_product='FEATURED', status='VERIFIED')
    products_all = Product.objects.filter(status='VERIFIED').order_by('?')
    wishlist_count = Wishlist.objects.filter(buyer_id=request.user.id).count()
    brand_products = Product.objects.filter(product_brand=brand).order_by("?")
    mod = os.path.dirname(__file__)
    file = os.path.join(mod, 'county.json')

    # with open(file) as f:
    #     print()
    #     data = f.read()
    #     # print(data.split('¿', 1)[1])
    #     json_data = json.loads(data.split('¿', 1)[1])
    #
    #     for p in json_data:
    #         County.objects.create(
    #            number=p['county_number'],
    #            name=p['county']
    #
    #         )
    #         print(p['county_number'], p['county'])


    context ={
        'title':'Mashkys',
        'user': user,
        'carousels' : carousels,
        'featured_products': featured_products,
        # 'products': products,
        'product_brands':brand_products,
        'products':products_all,
        'wishlist_count':wishlist_count,
        'brand':brand,
        # 'categories':categories,
        # 'orderproducts': orderproducts
    }
    return render(request, 'shoppy/home.html', context)





@login_required()
def addToWishlist(request, product_id, source):

    product = Product.objects.filter(id=product_id).first()
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    print(buyer)
    print(product)

    if buyer is not None and product is not None:
        Wishlist.objects.create(buyer=buyer, product=product)
        # messages.success(request, '')
        sweetify.success(request,  'Added successfully', timer=3000)
    else:
        # messages.error(request, '')
        sweetify.error(request, title='Error' 'Could not add product', button='ok', timer=5000)


    source = source.replace('____', '/')
    return redirect(source)


@login_required()
def unWishProduct(request, wishlist_id, source):
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    wishlist = Wishlist.objects.filter(id=wishlist_id)
    if buyer is not None:
        wishlist.delete()
        sweetify.success(request,  'Your Wish Have Been Removed', button='ok', timer=3000)
        # messages.success(request, '')
    source = source.replace('____', '/')
    return redirect(source)


@login_required()
def unWish_All_Products(request):
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    wishlist = Wishlist.objects.all().filter(buyer_id=request.user.id)
    if buyer is not None:

        wishlist.delete()
        sweetify.success(request,  'All Your Wishes Have Been Removed', button='ok', timer=3000)
        # messages.success(request, '')
    return redirect('Shoppy:shoppy-user_account')

# cart
def cart(request):

    carts = Order_Product.objects.filter(buyer_id=request.user.id, checkout__isnull=True, product__wishlist__isnull=True)
    order_varianto = OrderProductVariantOption.objects.all()
    buyer =  Buyer.objects.filter(user_ptr_id=request.user.id).first()
    # variant =  Variant.objects.filter()
    # variant = Variant.objects.filter(variant_options__orderproductvariantoption__orderProduct_id=
    # s)
    # print(cart)
    context = {
        'carts' : carts,
        'title': 'Shoppy-Cart',
        'ordervarianto': order_varianto,
        'buyer':buyer,

    }
    return render(request, 'shoppy/cart.html', context)

@login_required()
def addCart(request, product_id):

    product = Product.objects.filter(id=product_id).first()
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()

    if request.method == 'POST':
        quantity = request.POST.get('quantity')
        unit_cost = request.POST.get('unit_cost')
        total = (float(unit_cost) * int(quantity))
        request.POST = request.POST.copy()
        # request.POST['total'] = total
        request.POST['buyer'] = buyer
        options = request.POST.getlist('variant_options[]')


        orderProduct = Order_Product.objects.create(
            product=product,
            buyer=buyer,
            quantity=quantity,
            total=total,
        )
        if options is not None:
            for variantoption in options:
                variant_option = Variant_Option.objects.filter(id=variantoption).first()
                OrderProductVariantOption.objects.create(
                    variantOptions=variant_option,
                    orderProduct=orderProduct,
                )
        sweetify.success(request,  'Product Added To Cart', button='ok', timer=3000)

        return redirect('Shoppy:shoppy-home')
    return redirect('Shoppy:shoppy-home')

def deleteCartProduct(request, order_id):
    cart_product = Order_Product.objects.filter(id=order_id).first()
    cart_product.delete()
    return redirect("Shoppy:shoppy-cart")


def productDetails(request, product_id):
    product = Product.objects.filter(id=product_id).first()
    images = Image.objects.filter(product= product_id)
    review_images = Image.objects.filter(product=product_id)[:2]
    reviews = Review.objects.filter(product=product).order_by('-created_at')
    product_carts = Product.objects.filter(id=product_id)
    similar_products= Product.objects.filter( product_brand=product.product_brand)
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()

    if request.method == 'POST':
        ratings = request.POST.get('ratings', False)
        comments = request.POST['comments']
        productt = request.POST['product']
        product = Product.objects.filter(id=productt).first()
        Review.objects.create(
            buyer=buyer,
            product=product,
            ratings=ratings,
            comments=comments,
        )
        sweetify.success(request, title='Success' 'Your Review Was Taken', button='ok', timer=3000)

    # sweetify.error(request, title='Error' 'You Can Only Review Products You Have Bought ', button='ok', timer=5000)


    context={
        'product' : product,
        'images' : images,
        'review_images': review_images,
        'similar_products':similar_products,
        'product_carts': product_carts,
        'reviews': reviews,

    }

    return render(request, 'shoppy/product_details.html',context)

def productsList(request, category_id):
    # products = Product.objects.filter(status='VERIFIED')
    max_cost=Product.objects.order_by('-unit_cost')[0]
    category= Category.objects.filter(id=category_id).first()
    products= Product.objects.filter(status='VERIFIED', category_id=category.id).order_by('-unit_cost')

    context={
        'products':products,
        'categories':Category.objects.all(),
        'brands':Brand.objects.all(),
        'max_cost':max_cost,

    }

    return render(request, 'shoppy/view_products/all_products.html', context)




# def productReview(request):
#     buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
#     if buyer is not None:
#         if request.method == 'POST':
#             ratings = request.POST.get('ratings', False)
#             comments = request.POST['comments']
#             productt = request.POST['product']
#             product = Product.objects.filter(id=productt).first()
#             Review.objects.create(
#                 buyer=buyer,
#                 product=product,
#                 ratings=ratings,
#                 comments=comments,
#             )
#             sweetify.success(request, title='Success' 'Your Review Was Taken', button='ok', timer=3000)
#             return redirect("Shoppy:shoppy_product_details")
#     sweetify.error(request, title='Error' 'You Can Only Review Products You Have Bought ', button='ok', timer=5000)
#     return redirect("Shoppy:shoppy_product_details")

# def user_account_product(request, product_id):
#     similar =Product.objects.filter(id=product_id).first()

Tulia_admin/templates/tulia/payments/payment.html
{% extends 'tulia/dashboard/dashboard.html' %}
{% load humanize %}
{% load static %}
{% block content %}
    <div class="dashboard-wrapper">
            <div class="container-fluid  dashboard-content">
                <!-- ============================================================== -->
                <!-- pageheader -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="page-header">
                            <h2 class="pageheader-title">Payments</h2>

                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- end pageheader -->
                <!-- ============================================================== -->
                <div class="row">
                    <!-- ============================================================== -->
                    <!-- basic table  -->
                    <!-- ============================================================== -->


                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="card">
                            <h5 class="card-header">Payments</h5>
                            <a href="" data-toggle="modal" data-target="#add_payment" class="btn-success btn pull-right">Record Order Payment</a>
                            <div class="card-body">
                                <div class="table-responsive">
                                     <table id="example" class="table table-striped table-bordered" style="width:100%;">
                                        <thead>
                                            <tr class="text-capitalize">
                                                <th>Id</th>
                                                <th>Buyer </th>
                                                <th>Phone Number</th>
                                                <th>Checkout Refrence</th>
                                                <th>Amount Paid</th>
                                                <th>Required Amount</th>
                                                <th>Balance</th>
                                                <th>Shipping cost</th>

                                                <th>Reciept No</th>
                                                <th>Date Recorded</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                                {% for pay in payments %}
                                                    <tr>
                                                        <td class="tb-data">{{ forloop.counter }}</td>

                                                        <td class="tb-data text-capitalize">
                                                            {% if pay.checkout.status == "PENDING" %}
                                                                <span style="color:#FEAA12;">{{ pay.checkout.buyer.first_name }} {{ pay.checkout.buyer.last_name }}</span>
                                                            {% else %}
                                                                {{ pay.checkout.buyer.first_name }} {{ pay.checkout.buyer.last_name }}
                                                            {% endif %}
                                                        </td>


                                                        <td class="tb-data text-capitalize">
                                                            {{ pay.checkout.buyer.phone_number }}
                                                        </td>

                                                        <td>{{ pay.checkout.reference_code }} </td>
                                                        <td>{{ pay.amount|floatformat|intcomma }} Ksh</td>
                                                        <td>{{ pay.checkout.total|floatformat|intcomma }} Ksh</td>
                                                        <td>{{ pay.balance|floatformat|intcomma}} Ksh</td>
                                                        <td>{{ pay.checkout.shipping_cost|floatformat|intcomma }} Ksh</td>

                                                        <td>{{ pay.payment_refrence }} </td>
                                                        <td class="tb-data">{{ pay.created_at|naturaltime }}</td>
                                                        <td class="text-center tb-data">
                                                            <a href="{% url 'TuliaAdmin:buyer_orders' pay.checkout.reference_code %}"  class="btn btn-info"><i class="fas fa-pencil-alt"></i> View</a>
                                                            <a href="#" data-toggle="modal" data-target="#pay{{ pay.id }}" class="btn btn-success"><i class="fas fa-pencil-alt"></i> Edit</a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                        </tbody>
                                     </table>
                                </div>
                            </div>
                        </div>
                    </div>


                    <!-- ============================================================== -->
                    <!-- end basic table  -->
                    <!-- ============================================================== -->
                </div>

            </div>
                {% for pay in payments %}
                     <div class="modal fade" id="pay{{ pay.id }}" role="dialog">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal">&times;</button>
                              <h4 class="modal-title"> Record New Order Payment</h4>
                            </div>
                            <div class="modal-body">
                             <fieldset>
                                 <form action="{% url 'TuliaAdmin:updated_payments' pay.id %}" method="POST">
                                 {% csrf_token %}
                                     <div class="form-group ">
                                         <h2>{% for chc in checkouts %}{{chc.reference_code}}-> {{ chc.total|floatformat|intcomma }} Kshs{% endfor %}</h2>

                                    </div>
                                    <div class="form-group has-feedback  col-sm-12">
                                      <label for="sel1">Amount Paid {{ pay.amount|floatformat:0 }} ksh</label> <br>
                                        <input required {% comment %}value="{{ pay.amount|floatformat:0 }}"{% endcomment %}  id="sel1" type="number" name="amount" class="form-control form">
                                    </div>
                                    <div class="form-group has-feedback  col-sm-12">
                                      <label for="sel1">Shipping Cost {{ pay.checkout.shipping_cost |floatformat:0}} Ksh</label> <br>
                                        <input id="sel1" value="{{ pay.checkout.shipping_cost |floatformat:0}}" type="number" name="shipping_cost" class="form-control form">
                                    </div>

                                     <div class="form-group has-feedback  col-sm-12">
                                      <label for="sel1">Reciept Number</label> <br>
                                        <input value="{{ pay.payment_refrence }}" required id="sel1" type="text" name="payment_reference" class="form-control form">
                                    </div>

                                    <div class="paddingy2">
                                        <button type="submit" class="btn btn-success product-button"> <i class="fas fa-plus"></i> Save</button>
            {#                            <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-close"></i> Close</button>#}
                                    </div>
                                 </form>
                             </fieldset>
                            </div>
                          </div>
                        </div>
                      </div>
                {% endfor %}
                     <div class="modal fade" id="add_payment" role="dialog">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal">&times;</button>
                              <h4 class="modal-title">Record Order Payment</h4>
                            </div>
                            <div class="modal-body">
                             <fieldset>
                                 <form action="{% url 'TuliaAdmin:payments' %}" method="POST">
                                 {% csrf_token %}
                                     <div class="form-group ">
                                      <label class="control-label" for="checkout">Checkout Order Number</label><br>
                                      <select required name="ref_code" autofocus id="checkout" class="form-control w-100">
                                          <option selected disabled>Choose A Order Number</option>
                                          {% for chc in checkouts %}
                                             <option value="{{chc.reference_code}}">{{chc.reference_code}}-> {{ chc.total|floatformat|intcomma }} Kshs</option>
                                          {% endfor %}
                                      </select>
                                    </div>
                                    <div class="form-group has-feedback  col-sm-12">
                                      <label for="sel1">Ammount</label> <br>
                                        <input required id="sel1" type="number" name="amount" class="form-control form">
                                    </div>
                                    <div class="form-group has-feedback  col-sm-12">
                                      <label for="sel1">Shipping Cost</label> <br>
                                        <input  id="sel1" value="0" type="number" name="shipping_cost" class="form-control form">
                                    </div>

                                     <div class="form-group has-feedback  col-sm-12">
                                      <label for="sel1">Reciept Number</label> <br>
                                        <input required id="sel1" type="text" name="payment_reference" class="form-control form">
                                    </div>

                                    <div class="paddingy2">
                                        <button type="submit" class="btn btn-success product-button"> <i class="fas fa-plus"></i> Add</button>
                {#                            <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-close"></i> Close</button>#}
                                    </div>
                                 </form>
                             </fieldset>
                            </div>
                          </div>
                        </div>
                     </div>
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <div class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
{#                            Copyright © 2018 Concept. All rights reserved. Dashboard by <a href="https://colorlib.com/wp/">Colorlib</a>.#}
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
                            <div class="text-md-right footer-links d-none d-sm-block">
                                <a href="javascript: void(0);">About</a>
                                <a href="javascript: void(0);">Support</a>
                                <a href="javascript: void(0);">Contact Us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- end footer -->
            <!-- ============================================================== -->
        </div>
{% endblock content %}

  {% block scripts %}

  {% endblock scripts %}